# -*- coding: utf-8 -*-
"""ChurnBinaryLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnRMXd35N5AZYNDSFQ9X_HUT2IFE7o1T
"""

import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
drive.mount('/content/drive')

path='/content/drive/MyDrive/churn_dataset.csv'
Db=pd.read_csv(path)
Db.drop(['customerID'], axis=1, inplace=True)
Db.dropna(inplace=True)
Db = pd.get_dummies(Db, columns=['InternetService', 'Contract', 'PaymentMethod','MultipleLines','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies'], drop_first=False)
binary_columns = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']
Db[binary_columns] = Db[binary_columns].replace({'Yes': 1, 'No': 0})
Db['gender'] = Db['gender'].map({'Male': 1, 'Female': 0})
columns = [ 'InternetService_DSL', 'InternetService_Fiber optic', 'InternetService_No', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year','PaymentMethod_Bank transfer (automatic)', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check','DeviceProtection_Yes','DeviceProtection_No','DeviceProtection_No internet service','TechSupport_Yes','TechSupport_No','TechSupport_No internet service','StreamingTV_Yes','StreamingTV_No','StreamingTV_No internet service','StreamingMovies_Yes','StreamingMovies_No','StreamingMovies_No internet service']
Db[columns] = Db[columns].astype(int)

X = Db.drop('Churn_binary', axis=1)
Y = Db['Churn_binary']
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size =.2,random_state=43)
X_train_ , X_val , Y_train_ , Y_val = train_test_split(X_train,Y_train,test_size =.2,random_state=43)
Scaler = RobustScaler()
X_train_ = Scaler.fit_transform(X_train_)
X_val = Scaler.transform(X_val)
X_test = Scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
lr_model = LogisticRegression()
lr_model.fit(X_train_, Y_train_)
train_preds = lr_model.predict(X_train_)
train_acc = accuracy_score(Y_train_, train_preds)
print(f"Training Accuracy: {train_acc * 100:.2f}%")
y_pred = lr_model.predict(X_test)
print(f"Accuracy: {accuracy_score(Y_test, y_pred):.4f}")

import joblib
joblib.dump(lr_model, 'lr_model.pkl')
joblib.dump(Scaler, 'scalerLR.pkl')