# -*- coding: utf-8 -*-
"""ChurnBinaryDT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlwYuFuUHjYMT8XbSiN-zNiahNpkVHJS
"""

import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from google.colab import drive
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
drive.mount('/content/drive')

path='/content/drive/MyDrive/churn_dataset.csv'
Db=pd.read_csv(path)
Db.drop(['customerID'], axis=1, inplace=True)
Db.dropna(inplace=True)
Db = pd.get_dummies(Db, columns=['InternetService', 'Contract', 'PaymentMethod','MultipleLines','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies'], drop_first=False)
binary_columns = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']
Db[binary_columns] = Db[binary_columns].replace({'Yes': 1, 'No': 0})
Db['gender'] = Db['gender'].map({'Male': 1, 'Female': 0})
columns = [ 'InternetService_DSL', 'InternetService_Fiber optic', 'InternetService_No', 'Contract_Month-to-month', 'Contract_One year', 'Contract_Two year','PaymentMethod_Bank transfer (automatic)', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check','DeviceProtection_Yes','DeviceProtection_No','DeviceProtection_No internet service','TechSupport_Yes','TechSupport_No','TechSupport_No internet service','StreamingTV_Yes','StreamingTV_No','StreamingTV_No internet service','StreamingMovies_Yes','StreamingMovies_No','StreamingMovies_No internet service']
Db[columns] = Db[columns].astype(int)

X = Db.drop('Churn_binary', axis=1)
Y = Db['Churn_binary']
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size =.2,random_state=43)
X_train_ , X_val , Y_train_ , Y_val = train_test_split(X_train,Y_train,test_size =.2,random_state=43)
Scaler = RobustScaler()
X_train_ = Scaler.fit_transform(X_train_)
X_val = Scaler.transform(X_val)
X_test = Scaler.transform(X_test)

from sklearn import tree
from sklearn.metrics import accuracy_score
clf = tree.DecisionTreeClassifier(
    max_depth=5,
    min_samples_leaf=10,
    min_samples_split=20,
)
clf = clf.fit(X_train_, Y_train_)
Y_pred = clf.predict(X_val)
accuracy_val = accuracy_score(Y_val, Y_pred)
Y_pred_ = clf.predict(X_test)
accuracy_test = accuracy_score(Y_test, Y_pred_)
print(accuracy_val)
print(accuracy_test)

import joblib
joblib.dump(clf, 'DT_model.pkl')
joblib.dump(Scaler, 'scalerDT.pkl')